### ISSUE TITLE
File indentation

### ISSUE THREAD

**Issue by gbence** [blackwinter/rb-gsl#11]
There are mixed tabs and spaces throughout the repository, that is very annoying if you are not used to it.  Is there any code style / guideline regarding this?

((If not then) an included "editor config" and/or) an indentation cleanup commit would be a good idea, preferably with:
```editorconfig
indent_style = space
indent_size = 2
```

**Comment by blackwinter** [comment]
I've cleaned up the whitespace now. After importing the [original gsl gem](https://rubygems.org/gems/gsl) I went through various steps of refactorings to improve the code base but style issues were only addressed as I came across them along the way. So thanks for pointing it out.
