### ISSUE TITLE
Missing tests for GSL::Permutation and GSL::Index

### ISSUE THREAD

**Issue by gbence** [blackwinter/rb-gsl#12]
There are no tests yet covering `GSL::Permutation` and `GSL::Index` -- which are fundamentally the same.

**Comment by blackwinter** [comment]
With the merge of #10 there are at least some for `GSL::Index#get`. Thanks for that! Would you be willing to expand those tests? I'd really appreciate it.

**Comment by gbence** [comment]
I'd love to do it but I can not take any deadlines. :)

**Comment by blackwinter** [comment]
No worries. I probably wouldn't get to it anytime soon myself. So thanks!

I leave it to you to either close this issue and come up with a pull request once you're ready, or leave it open as a reminder. I'm fine either way.
