### ISSUE TITLE
Commit history issue

### ISSUE THREAD

**Issue by ktns** [blackwinter/rb-gsl#14]
There is a repository that includes the commit history before 1.15.1.3.
https://github.com/david-macmahon/rb-gsl
What do you think about merging the past commits into your repository?
If you would like to merge them, the branch below which I prepared as a scaffold might be of some help.
https://github.com/ktns/rb-gsl/tree/commit_history

**Comment by blackwinter** [comment]
Thanks for the heads-up, but I'm not going to modify the history of this repo. Had I known david's repo when I started, I definitely would have forked it; no idea why I didn't come across it. Now it's too late, though.

However, I followed your lead and integrated it in a [branch of its own](/blackwinter/rb-gsl/tree/prehistory).
