### ISSUE TITLE
Multiplying float with GSL::Matrix::Int produces garbage

### ISSUE THREAD

**Issue by v0dro** [blackwinter/rb-gsl#16]
This was my result:

```

1.9.3-p551 :003 > a=GSL::Matrix::Int.ones(1)
 => GSL::Matrix::Int
[ 1 ] 
1.9.3-p551 :005 > 0.2 * a
 => GSL::Matrix::Int
[ 69706220 ] 
```

**Comment by blackwinter** [comment]
Unfortunately, I can't reproduce this error. The multiplication tests (a6e4f00) pass on [Travis](https://travis-ci.org/blackwinter/rb-gsl/jobs/61442028), too.

Could it be that your environment is somehow tainted? Could you try a clean recompile?

**Comment by v0dro** [comment]
I'll try that out
