### ISSUE TITLE
nmatrix support

### ISSUE THREAD

**Issue by minad** [blackwinter/rb-gsl#27]
This goes in the nmatrix branch. For now I copied the code from https://github.com/sciruby/rb-gsl. This doesn't work or compile yet. Maybe @v0dro wants to continue from here, since he already did some work concerning nmatrix?

**Comment by v0dro** [comment]
The code from sciruby/rb-gsl should not be used here. Its outdated and buggy.

Code you please replace that with v0dro/gsl-nmatrix? I've already written most of the [NMatrix converters](https://github.com/v0dro/gsl-nmatrix/blob/master/ext/gsl/gsl_nmatrix.c). Everything is tested and works fine. They just need to be merged with this fork.

**Comment by minad** [comment]
Maybe you merge the nmatrix branch with your code? :)

I will review it then and merge it to master if ready.

Am 21. Juni 2015 16:23:19 MESZ, schrieb Sameer Deshmukh <notifications@github.com>:

**Comment by v0dro** [comment]
Sure thing! :P
